<a href="https://colab.research.google.com/github/Manishkancharla/Python_Numpy_Data_Toolkit_Assignment/blob/main/Numpy_Data_Toolkit_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Theoretical Questions:


1)  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

In [1]:
# Advantages of NumPy in Scientific Computing :
# Performance and Speed: Written in C, NumPy is much faster than native Python lists due to optimized computations.
# Ease of Use: Simplifies complex mathematical operations with concise, readable syntax.
# Data Analysis and Processing: Supports efficient data manipulation, making it ideal for tasks like statistical analysis, simulations, and scientific research.
# Cross-Platform Compatibility: Works on various platforms and supports many file formats like CSV, Excel, and binary files.
# Data Storage and Interoperability: Facilitates reading/writing large datasets and exchanging data between different libraries.

# How NumPy Enhances Python's Numerical Capabilities :
# Faster Computation: Uses C-based implementation for performance-critical operations.
# Array Operations: Supports multi-dimensional array creation, slicing, and reshaping, making data manipulation straightforward.
# Efficient Memory Usage: Manages memory more efficiently by using fixed-type arrays and minimizing overhead.
# Vectorization and Broadcasting: Reduces the need for explicit loops, enabling vectorized computations that speed up calculations.
# Support for Complex Mathematical Operations: Implements numerical algorithms like matrix decomposition, Fourier transforms, and random number generation.
import numpy as np

# Create two large arrays
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# Perform element-wise addition using NumPy
result = a + b
print(f"First 5 results: {result[:5]}")


First 5 results: [0.33386075 0.44025031 0.72935449 1.02106511 1.42243628]


2)  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

In [3]:
# Both np.mean() and np.average() are used to compute the average value of elements in a NumPy array, but they have important differences in terms of functionality, flexibility, and use cases.
# np.mean() : Calculates the arithmetic mean (average) of array elements along a specified axis.
# Syntax : np.mean(array, axis=None, dtype=None)
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6]])
print("Mean of all elements:", np.mean(data))
print("Mean along rows:", np.mean(data, axis=1))



Mean of all elements: 3.5
Mean along rows: [2. 5.]


In [4]:
# np.average() : Calculates the weighted average of elements, optionally using specified weights.
# Syntax : np.average(array, axis=None, weights=None, returned=False)
weights = np.array([0.2, 0.3, 0.5])
values = np.array([70, 80, 90])

# Calculate weighted average
weighted_avg = np.average(values, weights=weights)
print("Weighted Average:", weighted_avg)


Weighted Average: 83.0


3)  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays?

In [5]:
# Reversing a NumPy array involves changing the order of elements along specified axes. This operation is useful in data preprocessing, manipulation, and analysis. Let’s explore methods for reversing arrays in different dimensions.
# Reversing a 1D NumPy Array :-
import numpy as np

# 1D Array
arr_1d = np.array([10, 20, 30, 40, 50])

# Reverse using slicing
reversed_1d = arr_1d[::-1]
print("Original 1D Array:", arr_1d)
print("Reversed 1D Array:", reversed_1d)


Original 1D Array: [10 20 30 40 50]
Reversed 1D Array: [50 40 30 20 10]


In [6]:
# Reversing a 2D NumPy Array :-
# 2D Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse rows
reverse_rows = arr_2d[::-1]
print("Original 2D Array:\n", arr_2d)
print("Rows Reversed:\n", reverse_rows)


Original 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rows Reversed:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


4)  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance?

In [7]:
# In NumPy, every array has a data type (dtype) that defines the type of elements stored in the array. You can determine this using various methods:
# Using dtype Attribute :-
import numpy as np

# Creating an array
arr = np.array([1, 2, 3, 4, 5])
print("Data Type:", arr.dtype)


Data Type: int64


In [8]:
# Using type() Function :-
print("Array Type:", type(arr))


Array Type: <class 'numpy.ndarray'>


In [9]:
# Specifying Data Type During Array Creation :-
arr_float = np.array([1, 2, 3], dtype=float)
print("Data Type:", arr_float.dtype)


Data Type: float64


In [11]:
# Using astype() for Type Conversion :-
# Convert to another data type
arr_converted = arr.astype(np.float32)
print("Converted Data Type:", arr_converted.dtype)

# Importance of Data Types in Memory Management and Performance :-
# Memory Efficiency: NumPy arrays use fixed-size memory blocks, determined by the data type.
# Example: int32 uses 4 bytes, while int64 uses 8 bytes. Choosing the correct data type minimizes memory usage.
# Performance Optimization: Fixed data types enable efficient storage and faster access to elements. Operations on homogeneous arrays are faster than on Python lists due to reduced overhead.
# Data Compatibility: Selecting an appropriate data type ensures compatibility with external systems, files, and libraries.
# Precision and Accuracy: Use float64 for high-precision calculations. Choose int8, int16, or float32 when memory usage matters more than precision.


Converted Data Type: float32


5) Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [12]:
# An ndarray (N-dimensional array) is the core data structure of the NumPy library. It represents a multi-dimensional, homogeneous array of fixed-size elements, all of the same data type (dtype). It supports efficient numerical computations and provides various methods for array operations.
# Key Features of ndarray in NumPy :-
# Multidimensional Structure: Supports arrays of any dimension (1D, 2D, 3D, etc.). Shape of the array is defined by a tuple of integers.
# Homogeneous Elements: All elements must have the same data type, ensuring efficient memory storage.
# Efficient Memory Management: Stored in contiguous memory blocks, enabling fast data access and operations.
# Broadcasting Support: Performs element-wise operations on arrays of different shapes through broadcasting.
# Built-in Functions: Supports built-in mathematical, statistical, and linear algebra functions.
# Indexing and Slicing: Advanced slicing, indexing, and boolean filtering capabilities.
# Type Flexibility: Supports many data types such as integers, floats, complex numbers, and custom data types.
# Integration: Works seamlessly with libraries like Pandas, SciPy, and TensorFlow.
# Comparison Between ndarray and Python List :-
# Element-wise Addition With Python Lists:
list_a = [1, 2, 3]
list_b = [4, 5, 6]

# Manual addition using list comprehension
result_list = [x + y for x, y in zip(list_a, list_b)]
print("List Result:", result_list)



List Result: [5, 7, 9]


In [13]:
# With NumPy ndarray :
import numpy as np

arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

# Element-wise addition
result_array = arr_a + arr_b
print("NumPy Array Result:", result_array)


NumPy Array Result: [5 7 9]


6) Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations?

In [14]:
# NumPy arrays (ndarray) offer significant performance advantages over Python lists for large-scale numerical operations due to several design optimizations. Let’s explore key aspects contributing to NumPy’s performance superiority.
# Memory Efficiency :-
# Fixed Data Type: All elements in a NumPy array have the same data type, unlike Python lists, which allow mixed types.
# Contiguous Memory Allocation: NumPy arrays are stored in contiguous memory blocks, enabling efficient memory management and reducing overhead.
import numpy as np
import sys

# Memory usage comparison
py_list = list(range(1000000))
np_array = np.arange(1000000)

print("Memory used by Python list:", sys.getsizeof(py_list), "bytes")
print("Memory used by NumPy array:", np_array.nbytes, "bytes")


Memory used by Python list: 8000056 bytes
Memory used by NumPy array: 8000000 bytes


In [15]:
# Speed and Performance :- Vectorized Operations: NumPy executes operations on entire arrays without explicit loops, leveraging low-level C-based functions for speed.Optimized Libraries: Built on C and Fortran libraries such as BLAS and LAPACK, ensuring high performance.
import numpy as np
import time

# Create large arrays
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# Using Python lists
start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start)

# Using NumPy arrays
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
result = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end - start)


Python list addition time: 0.10942339897155762
NumPy array addition time: 0.01962447166442871


7) Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output?

In [17]:
# NumPy’s vstack() and hstack() functions are used to combine arrays along different axes. Let’s explore the differences, usage, and examples for each.
# vstack() (Vertical Stack) :- Stacks arrays vertically (row-wise).
# Axis of Stacking: Along the first axis (axis=0).
# Requirement: Arrays must have the same number of columns.
import numpy as np

# 1D Arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical Stack
result_vstack = np.vstack((arr1, arr2))
print("Vertical Stack Result:\n", result_vstack)


Vertical Stack Result:
 [[1 2 3]
 [4 5 6]]


In [18]:
# hstack() (Horizontal Stack) :- Stacks arrays horizontally (column-wise).
# Axis of Stacking: Along the second axis (axis=1).
# Requirement: Arrays must have the same number of rows.
# 1D Arrays
arr5 = np.array([1, 2, 3])
arr6 = np.array([4, 5, 6])

# Horizontal Stack
result_hstack = np.hstack((arr5, arr6))
print("Horizontal Stack Result:\n", result_hstack)


Horizontal Stack Result:
 [1 2 3 4 5 6]


8)  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions?

In [19]:
# NumPy provides the functions fliplr() and flipud() to reverse elements along specific axes of arrays. Let’s break down how they work, their effects on different array dimensions, and key differences.
# fliplr() (Flip Left to Right) :- Reverses the columns of a 2D array (flips the array horizontally).
# Works only on arrays with two or more dimensions.
# Elements in each row are flipped left to right (horizontally).
# Affects axis=1 (columns).
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip Left to Right
result_fliplr = np.fliplr(arr)
print("Original Array:\n", arr)
print("After fliplr (Horizontal Flip):\n", result_fliplr)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After fliplr (Horizontal Flip):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [20]:
# flipud() (Flip Up to Down) :- Reverses the rows of an array (flips the array vertically).
# Works on arrays with one or more dimensions.
# Elements are flipped from top to bottom (vertically).
# Affects axis=0 (rows).
# Flip Up to Down
result_flipud = np.flipud(arr)
print("After flipud (Vertical Flip):\n", result_flipud)


After flipud (Vertical Flip):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


9)  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [21]:
# The numpy.array_split() function splits an array into multiple sub-arrays along a specified axis. It is more flexible than split() because it can handle uneven splits, meaning the resulting sub-arrays do not have to be of equal size.
# Syntax :- numpy.array_split(ary, indices_or_sections, axis=0)
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
result = np.array_split(arr, 3)
print("Even Split Result:", result)


Even Split Result: [array([1, 2]), array([3, 4]), array([5, 6])]


10) Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

In [22]:
# Vectorization and broadcasting are core features of NumPy that enable efficient numerical computations by eliminating explicit loops and leveraging optimized C-based implementations. These concepts contribute significantly to the speed and efficiency of array operations in Python.

import numpy as np

# Two lists
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

# Manual element-wise addition
result = [x + y for x, y in zip(a, b)]
print("Manual Addition:", result)


Manual Addition: [6, 8, 10, 12]


Practical Questions :-

1)  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns?

In [23]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))

# Print the original array
print("Original Array:\n", arr)

# Interchange rows and columns (Transpose the array)
transposed_arr = arr.T

# Print the transposed array
print("\nTransposed Array:\n", transposed_arr)


Original Array:
 [[93 33 90]
 [46 81 70]
 [89 95 18]]

Transposed Array:
 [[93 46 89]
 [33 81 95]
 [90 70 18]]


2)  Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array?

In [24]:
import numpy as np

# Generate a 1D array with 10 elements
arr_1d = np.arange(1, 11)

# Print the original 1D array
print("Original 1D Array:\n", arr_1d)

# Reshape into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:\n", arr_2x5)

# Reshape into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:\n", arr_5x2)


Original 1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


3) Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array?

In [25]:
import numpy as np

# Generate a 1D array with 10 elements
arr_1d = np.arange(1, 11)

# Print the original 1D array
print("Original 1D Array:\n", arr_1d)

# Reshape into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:\n", arr_2x5)

# Reshape into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:\n", arr_5x2)

# Create a 4x4 array with random float values
arr_4x4 = np.random.rand(4, 4)
print("\nOriginal 4x4 Array:\n", arr_4x4)

# Add a border of zeros to create a 6x6 array
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:\n", arr_6x6)


Original 1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

Original 4x4 Array:
 [[0.18172207 0.93206183 0.05589609 0.07738293]
 [0.76819859 0.39676774 0.24895416 0.4978685 ]
 [0.53490415 0.40475315 0.81549619 0.16776719]
 [0.11747322 0.04093426 0.85827259 0.11091153]]

6x6 Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.18172207 0.93206183 0.05589609 0.07738293 0.        ]
 [0.         0.76819859 0.39676774 0.24895416 0.4978685  0.        ]
 [0.         0.53490415 0.40475315 0.81549619 0.16776719 0.        ]
 [0.         0.11747322 0.04093426 0.85827259 0.11091153 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4)  Using NumPy, create an array of integers from 10 to 60 with a step of 5?

In [26]:
import numpy as np

# Generate a 1D array with 10 elements
arr_1d = np.arange(1, 11)

# Print the original 1D array
print("Original 1D Array:\n", arr_1d)

# Reshape into a 2x5 array
arr_2x5 = arr_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:\n", arr_2x5)

# Reshape into a 5x2 array
arr_5x2 = arr_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:\n", arr_5x2)

# Create a 4x4 array with random float values
arr_4x4 = np.random.rand(4, 4)
print("\nOriginal 4x4 Array:\n", arr_4x4)

# Add a border of zeros to create a 6x6 array
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Zero Border:\n", arr_6x6)

# Create an array of integers from 10 to 60 with a step of 5
arr_step = np.arange(10, 61, 5)
print("\nArray from 10 to 60 with step of 5:\n", arr_step)


Original 1D Array:
 [ 1  2  3  4  5  6  7  8  9 10]

Reshaped to 2x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped to 5x2 Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

Original 4x4 Array:
 [[0.925158   0.09094245 0.2297494  0.30863188]
 [0.83861912 0.61187522 0.05999675 0.73693792]
 [0.14716195 0.80568704 0.01597266 0.93136468]
 [0.87107207 0.53355328 0.67882791 0.44180791]]

6x6 Array with Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.925158   0.09094245 0.2297494  0.30863188 0.        ]
 [0.         0.83861912 0.61187522 0.05999675 0.73693792 0.        ]
 [0.         0.14716195 0.80568704 0.01597266 0.93136468 0.        ]
 [0.         0.87107207 0.53355328 0.67882791 0.44180791 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]

Array from 10 to 60 with step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


5) Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element?

In [27]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(arr)    # Convert to uppercase
lowercase = np.char.lower(arr)    # Convert to lowercase
titlecase = np.char.title(arr)    # Convert to title case
capitalize = np.char.capitalize(arr)  # Capitalize the first letter

# Display the results
print("Original:", arr)
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Titlecase:", titlecase)
print("Capitalize:", capitalize)


Original: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Titlecase: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


6) Generate a NumPy array of words. Insert a space between each character of every word in the array?

In [29]:
import numpy as np

# Create a NumPy array of words
arr = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_arr = np.array([' '.join(word) for word in arr])

# Display the result
print("Original:", arr)
print("Spaced:", spaced_arr)


Original: ['python' 'numpy' 'pandas']
Spaced: ['p y t h o n' 'n u m p y' 'p a n d a s']


7) Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division?

In [30]:
import numpy as np

# Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = arr1 + arr2

# Perform element-wise subtraction
subtraction = arr1 - arr2

# Perform element-wise multiplication
multiplication = arr1 * arr2

# Perform element-wise division
division = arr1 / arr2

# Display the results
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Element-wise Addition:\n", addition)
print("Element-wise Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]
Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8) Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements?

In [31]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Display the results
print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


9)  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array?

In [32]:
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1000, 100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Display the results
print("Random Array:", random_array)
print("Prime Numbers:", prime_numbers)


Random Array: [494 474 484 252 822 652 671 435 288 880  26  81 238  60 421 719  33 520
 465 927 506 350 280 312  98 840 445 704 165 601 648 283 236 704 770 583
 949 518 338 818 871 949  69 207 761 738 856 938 998 213 101 767 988 297
 156 100 387 765 219 446 855 490 290 210 366 986 463 656 891 637  52  67
 423 959 193 697 732 376 132 668 878 612 936 620 256 348 299 342 642 864
 607 122 706 908 723 321 711 761 390 751]
Prime Numbers: [421, 719, 601, 283, 761, 101, 463, 67, 193, 607, 761, 751]


10) Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages?

In [33]:
import numpy as np

# Generate a NumPy array representing daily temperatures for a month (30 days)
# Let's use random temperatures between 15 and 30 degrees Celsius
daily_temperatures = np.random.randint(15, 31, 30)

# Reshape the array into weeks (4 full weeks + 1 partial week)
weekly_temperatures = daily_temperatures.reshape(5, 6)

# Calculate the weekly averages
weekly_averages = weekly_temperatures.mean(axis=1)

# Display the results
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Temperatures (reshaped into weeks):\n", weekly_temperatures)
print("Weekly Averages:", weekly_averages)


Daily Temperatures for the Month: [26 18 25 25 21 26 23 18 18 22 21 18 18 27 21 28 15 26 28 30 18 29 22 27
 24 24 29 22 23 16]
Weekly Temperatures (reshaped into weeks):
 [[26 18 25 25 21 26]
 [23 18 18 22 21 18]
 [18 27 21 28 15 26]
 [28 30 18 29 22 27]
 [24 24 29 22 23 16]]
Weekly Averages: [23.5        20.         22.5        25.66666667 23.        ]
